### ISSUE TITLE
Python 3.11 missing?

### ISSUE THREAD

**Issue by samjarrett** [renovatebot/docker-renovate-full#2718]
Hello!

Hopefully I've got the right repo to report this in. We use renovate via the [github action](https://github.com/renovatebot/github-action). We configure it like this:

```yaml
    - id: renovate-scan
      name: Renovate
      uses: renovatebot/github-action@v39.2.3
      with:
        renovate-version: full
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        RENOVATE_REPOSITORIES: ""  # repo path
        LOG_LEVEL: debug
```

When it encounters python 3.11 in use, it adds the following comment:

### ⚠ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻ Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you click the rebase/retry checkbox if found above, or
 - you rename this PR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: Pipfile.lock

```
Command failed: pipenv lock
Warning: Python 3.11 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
```

This is only an issue with python 3.11. 3.10 and below work without issue.
